# Generated by Django 2.0.2 on 2018-02-24 17:58

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidate', '0010_auto_20180224_1738'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsStory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', model_utils.fields.StatusField(choices=[('Unpublished', 'Unpublished'), ('Published', 'Published')], default='Unpublished', max_length=100, no_check_for_status=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('teaser', ckeditor.fields.RichTextField(blank=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to='candidate.Candidate')),
            ],
        ),
    ]
