# Generated by Django 2.0.2 on 2018-02-24 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20180224_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsstory',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='newsstory',
            name='link',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
