# Generated by Django 2.0.2 on 2018-02-20 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
