# Generated by Django 2.0.2 on 2018-02-20 01:13

from django.db import migrations
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0002_candidate_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='state',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='AL', max_length=100, no_check_for_status=True),
        ),
    ]
