# Generated by Django 2.0.2 on 2018-02-24 16:30

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0004_candidate_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='bio',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
