# Generated by Django 2.0.2 on 2018-02-24 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0005_candidate_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='campaign_city',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='candidate',
            name='campaign_coords',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='candidate',
            name='campaign_street',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='candidate',
            name='campaign_street2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='candidate',
            name='campaign_zip',
            field=models.CharField(blank=True, max_length=9),
        ),
    ]
