# Generated by Django 2.0.2 on 2018-02-24 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0006_auto_20180224_1652'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='campaign_coords',
            new_name='campaign_lat',
        ),
        migrations.AddField(
            model_name='candidate',
            name='campaign_long',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
