# Generated by Django 2.0.2 on 2018-02-24 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0009_auto_20180224_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidateissue',
            name='candidate',
        ),
        migrations.RemoveField(
            model_name='candidateissue',
            name='issue',
        ),
        migrations.DeleteModel(
            name='CandidateIssue',
        ),
        migrations.DeleteModel(
            name='Issue',
        ),
    ]
