# Generated by Django 2.0.2 on 2018-02-24 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0010_auto_20180224_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='facebook_follower',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='twitter_follower',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
