# Generated by Django 2.0.2 on 2018-02-24 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0014_candidate_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='identifier',
            field=models.CharField(blank=True, max_length=1064),
        ),
    ]
