# Generated by Django 2.0.2 on 2018-02-24 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0015_candidate_identifier'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ethnicity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=1064)),
            ],
        ),
        migrations.AddField(
            model_name='candidate',
            name='ethnicity',
            field=models.ManyToManyField(to='candidate.Ethnicity'),
        ),
    ]
