# Generated by Django 2.0.2 on 2018-03-08 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0019_issue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='parent',
        ),
        migrations.DeleteModel(
            name='Issue',
        ),
    ]
