# Generated by Django 2.0.2 on 2018-03-24 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0022_auto_20180308_1757'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ethnicity',
            options={'verbose_name_plural': 'Ethnicities'},
        ),
        migrations.AddField(
            model_name='candidate',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
