# Generated by Django 2.0.2 on 2018-03-24 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0023_auto_20180324_1834'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateInvite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=1025)),
                ('md5_email', models.CharField(editable=False, max_length=16)),
            ],
        ),
    ]
