# Generated by Django 2.0.2 on 2018-03-24 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0024_candidateinvite'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateinvite',
            name='candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='candidate.Candidate'),
        ),
        migrations.AddField(
            model_name='candidateinvite',
            name='used',
            field=models.BooleanField(default=False),
        ),
    ]
