# Generated by Django 2.0.2 on 2018-03-24 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0026_auto_20180324_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateinvite',
            name='name',
            field=models.CharField(blank=True, max_length=1025),
        ),
    ]
