# Generated by Django 2.0.2 on 2018-03-24 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0027_candidateinvite_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateinvite',
            name='emailed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
