# Generated by Django 2.0.2 on 2018-03-24 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0028_auto_20180324_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateinvite',
            name='md5_email',
            field=models.CharField(editable=False, max_length=32),
        ),
    ]
