# Generated by Django 2.0.2 on 2018-03-27 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0030_candidate_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='homepage',
            field=models.BooleanField(default=False),
        ),
    ]
