# Generated by Django 2.0.2 on 2018-03-27 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0031_candidate_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='unique_identifier',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
