# Generated by Django 2.0.2 on 2018-04-25 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0035_auto_20180407_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateinvite',
            name='name',
            field=models.CharField(max_length=1025),
        ),
    ]
