# Generated by Django 2.0.2 on 2018-04-26 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0037_auto_20180425_2353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidateinvite',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='candidateinvite',
            name='last_name',
            field=models.CharField(default='mallon', max_length=1025),
            preserve_default=False,
        ),
    ]
