# Generated by Django 2.0.2 on 2018-06-17 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0005_auto_20180429_2326'),
        ('candidate', '0038_auto_20180426_0004'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='issue1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issue1', to='issue.CandidateIssue'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='issue2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issue2', to='issue.CandidateIssue'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='issue3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issue3', to='issue.CandidateIssue'),
        ),
    ]
