# Generated by Django 2.0.2 on 2018-06-17 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0039_auto_20180617_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='issue1',
            field=models.CharField(blank=True, max_length=1064, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='issue2',
            field=models.CharField(blank=True, max_length=1064, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='issue3',
            field=models.CharField(blank=True, max_length=1064, null=True),
        ),
    ]
