# Generated by Django 2.0.2 on 2018-06-17 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0040_auto_20180617_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='campaign_lat',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='campaign_long',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
