# Generated by Django 2.0.2 on 2018-06-25 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0044_auto_20180625_2238'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=1025)),
                ('first_name', models.CharField(max_length=1025)),
                ('last_name', models.CharField(max_length=1025)),
                ('updated', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Candidate Update',
            },
        ),
        migrations.AlterField(
            model_name='candidate',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Headshot'),
        ),
        migrations.AddField(
            model_name='candidateupdate',
            name='candidate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='candidate.Candidate'),
        ),
    ]
