# Generated by Django 2.0.2 on 2018-06-26 01:18

from django.db import migrations
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0045_auto_20180625_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='approval',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], db_index=True, default='Approved', max_length=100, no_check_for_status=True),
        ),
    ]
