# Generated by Django 2.0.2 on 2018-06-26 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0046_candidate_approval'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='unique_identifier',
            new_name='unique_identifier1',
        ),
        migrations.AddField(
            model_name='candidate',
            name='unique_identifier2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
