# Generated by Django 2.0.2 on 2018-06-26 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0047_auto_20180626_0129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='identifier',
        ),
        migrations.AddField(
            model_name='candidate',
            name='filing_number',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
