# Generated by Django 2.0.2 on 2018-06-26 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0048_auto_20180626_0141'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='referral',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
