# Generated by Django 2.0.2 on 2018-06-26 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0049_candidate_referral'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateupdate',
            name='candidate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='candidate.Candidate'),
        ),
    ]
