# Generated by Django 2.0.2 on 2018-06-26 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0050_auto_20180626_2300'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateReferral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1025)),
            ],
            options={
                'verbose_name_plural': 'Candidate Referrals',
            },
        ),
    ]
