# Generated by Django 2.0.2 on 2018-06-26 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0051_candidatereferral'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidatereferral',
            options={'verbose_name_plural': 'Candidate Referral Source'},
        ),
    ]
