# Generated by Django 2.0.2 on 2018-07-01 22:08

from django.db import migrations, models
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0052_auto_20180626_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='issue1_detail',
            field=models.TextField(blank=True, max_length=280),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='issue2_detail',
            field=models.TextField(blank=True, max_length=280),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='issue3_detail',
            field=models.TextField(blank=True, max_length=280),
        )
    ]
