# Generated by Django 2.0.2 on 2018-07-01 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0053_auto_20180701_2208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='unique_identifier1',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='unique_identifier2',
        ),
    ]
