# Generated by Django 2.0.2 on 2018-07-23 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0054_auto_20180701_2358'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='man',
            field=models.BooleanField(default=False),
        ),
    ]
