# Generated by Django 2.0.2 on 2018-07-01 22:15

from django.db import migrations
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0054_auto_20180701_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='unique_identifier1',
            field=model_utils.fields.StatusField(blank=True, choices=[(0, 'dummy')], default=None, max_length=100, no_check_for_status=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='unique_identifier2',
            field=model_utils.fields.StatusField(blank=True, choices=[(0, 'dummy')], default=None, max_length=100, no_check_for_status=True, null=True),
        ),
    ]
