# Generated by Django 2.0.2 on 2018-07-01 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0056_auto_20180701_2306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='lgbtq',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='marginalized',
        ),
    ]
