# Generated by Django 2.0.2 on 2018-07-24 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0057_auto_20180724_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateupdate',
            name='note',
            field=models.TextField(blank=True),
        ),
    ]
