# Generated by Django 2.0.2 on 2018-07-24 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0058_candidateupdate_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='race_name',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
