# Generated by Django 2.0.2 on 2018-07-24 18:06

from django.db import migrations, models
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0059_candidate_race_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='race_name',
            field=models.CharField(blank=True, help_text='Only internal field, must populate actual race', max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='state',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], db_index=True, default=None, max_length=100, no_check_for_status=True),
        ),
    ]
