# Generated by Django 2.0.2 on 2018-03-30 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raceentry',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidate.Candidate'),
        ),
        migrations.AlterField(
            model_name='raceentry',
            name='race',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='races.Race'),
        ),
    ]
