# Generated by Django 2.0.2 on 2018-04-01 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0002_auto_20180330_0200'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='state',
            options={'ordering': ['state']},
        ),
    ]
