# Generated by Django 2.0.2 on 2018-04-01 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0003_auto_20180401_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raceentry',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='candidate.Candidate'),
        ),
        migrations.AlterField(
            model_name='raceentry',
            name='race',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='races', to='races.Race'),
        ),
    ]
