# Generated by Django 2.0.2 on 2018-04-25 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0004_auto_20180401_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='election_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='race',
            name='primary_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
