# Generated by Django 2.0.2 on 2018-03-13 23:10

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0004_state_seal'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='bio',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='state',
            name='seal',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
