# Generated by Django 2.0.2 on 2018-03-14 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0005_auto_20180313_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='open_race',
            field=models.BooleanField(default=False),
        ),
    ]
