# Generated by Django 2.0.2 on 2018-04-25 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0005_auto_20180425_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='caucus_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
