# Generated by Django 2.0.2 on 2018-03-27 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0006_race_open_race'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='filing_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
