# Generated by Django 2.0.2 on 2018-03-29 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0007_race_filing_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='other',
            field=models.CharField(blank=True, help_text='If there is another descriptor for the race', max_length=255),
        ),
    ]
