# Generated by Django 2.0.2 on 2018-03-29 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0008_race_other'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='race',
            name='open_race',
        ),
    ]
