# Generated by Django 2.0.2 on 2018-07-01 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0008_auto_20180425_2246'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='race',
            options={'ordering': ['pk']},
        ),
    ]
