# Generated by Django 2.0.2 on 2018-08-12 18:21

from django.db import migrations
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0010_auto_20180724_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='race_type',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='US Senate', max_length=100, no_check_for_status=True),
        ),
    ]
