# Generated by Django 2.0.2 on 2018-03-24 19:10

from django.db import migrations
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180324_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='state',
            field=model_utils.fields.StatusField(blank=True, choices=[(0, 'dummy')], default='AL', max_length=100, no_check_for_status=True),
        ),
    ]
