# Generated by Django 2.0.2 on 2018-03-24 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180324_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='opt_in',
            field=models.BooleanField(default=True),
        ),
    ]
