from model_utils import Choices

IDENTIFIER = Choices((None, '---'),
                    'Adopted',
                    'Adopted child(ren)',
                    'Animal enthusiast',
                    'Animal Rescuer',
                    'Antique collector',
                    'Avid reader',
                    'Bicyclist',
                    'Boater',
                    'Born to travel',
                    'Bowler',
                    'Chef',
                    'Chiropractor',
                    'Crafter',
                    'Dancer',
                    'Dentist',
                    'Disabled',
                    'Disabled spouse/child',
                    'Disabled Veteran',
                    'Doctor',
                    'Eye Doctor',
                    'Farmer',
                    'Gardener',
                    'Golfer',
                    'Grandmother',
                    'Happy Camper',
                    'Holistic therapist',
                    'Identifies as Marginalized',
                    'Lawyer',
                    'LBGQT',
                    'Mother',
                    'Motorcyclist',
                    'Mountaineer',
                    'Nurse',
                    'Other',
                    'Photographer',
                    'Pilot',
                    'Quilter',
                    'Referee',
                    'RV-er',
                    'Scout leader',
                    'Single parent',
                    'Soccer/sports mom',
                    'Sportfishing',
                    'Swimmer',
                    'Team sports',
                    'Tennis player',
                    'Veteran',
                    'Veterinarian',
                    'Widow',
                    'Wine Connoisseur',
                    'Working Mother',
                    'Writer',
                    'Yoga follower')