from model_utils import Choices

IDENTIFIER = Choices((None, '---'),
                    'Adopted',
                    'Adopted child(ren)',
                    'Animal enthusiast',
                    'Animal Rescuer',
                    'Antique collector',
                    'Avid reader',
                    'Bicyclist',
                    'Boater',
                    'Born to travel',
                    'Bowler',
                    'Chef',
                    'Chiropractor',
                    'Crafter',
                    'Dancer',
                    'Dentist',
                    'Disabled',
                    'Disabled spouse/child',
                    'Disabled Veteran',
                    'Doctor',
                    'Eye Doctor',
                    'Farmer',
                    'Gardener',
                    'Golfer',
                    'Grandmother',
                    'Happy Camper',
                    'Holistic therapist',
                    'Identifies as Marginalized',
                    'Lawyer',
                    'LBGQT',
                    'Mother',
                    'Motorcyclist',
                    'Mountaineer',
                    'Nurse',
                    'Other',
                    'Photographer',
                    'Pilot',
                    'Quilter',
                    'Referee',
                    'RV-er',
                    'Scout leader',
                    'Single parent',
                    'Soccer/sports mom',
                    'Sportfishing',
                    'Swimmer',
                    'Team sports',
                    'Tennis player',
                    'Veteran',
                    'Veterinarian',
                    'Widow',
                    'Wine Connoisseur',
                    'Working Mother',
                    'Writer',
                    'Yoga follower')

OPT_OPTIONS = Choices((None, '---'),
                      ('Yes', 'Yes'),
                      ('No', 'No'),
                      ('No Response', 'Choose not to respond')
                      )

STATES = Choices(('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'),
                     ('AR', 'Arkansas'), ('CA', 'California'),
                     ('CO', 'Colorado'), ('CT', 'Connecticut'),
                     ('DE', 'Delaware'), ('DC', 'District of Columbia'),
                     ('FL', 'Florida'), ('GA', 'Georgia'),
                     ('HI', 'Hawaii'),
                     ('ID', 'Idaho'), ('IL', 'Illinois'),
                     ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'),
                     ('KY', 'Kentucky'),
                     ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'),
                     ('MA', 'Massachusetts'), ('MI', 'Michigan'),
                     ('MN', 'Minnesota'),
                     ('MS', 'Mississippi'), ('MO', 'Missouri'),
                     ('MT', 'Montana'),
                     ('NE', 'Nebraska'), ('NV', 'Nevada'),
                     ('NH', 'New Hampshire'),
                     ('NJ', 'New Jersey'), ('NM', 'New Mexico'),
                     ('NY', 'New York'),
                     ('NC', 'North Carolina'), ('ND', 'North Dakota'),
                     ('OH', 'Ohio'),
                     ('OK', 'Oklahoma'), ('OR', 'Oregon'),
                     ('PA', 'Pennsylvania'),
                     ('RI', 'Rhode Island'), ('SC', 'South Carolina'),
                     ('SD', 'South Dakota'),
                     ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'),
                     ('VT', 'Vermont'), ('VA', 'Virginia'),
                     ('WA', 'Washington'),
                     ('WV', 'West Virginia'), ('WI', 'Wisconsin'),
                     ('WY', 'Wyoming'))

PARTY = Choices('Democrat', 'Republican',
                'Independent', 'Green',
                'Not Listed', 'Non-Partisian')

ORG_TYPE = Choices('Training',
                   'Public Policy',
                   'Advocacy')