# Generated by Django 2.0.2 on 2018-02-24 17:44

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='desc',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
