# Generated by Django 2.0.2 on 2018-02-25 00:13

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0002_issue_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='desc',
        ),
        migrations.AddField(
            model_name='candidateissue',
            name='desc',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
