# Generated by Django 2.0.2 on 2018-07-24 18:06

from django.db import migrations
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_auto_20180702_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultant',
            name='state',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], db_index=True, default=None, max_length=100, no_check_for_status=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='state',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], db_index=True, default=None, max_length=100, no_check_for_status=True),
        ),
    ]
