# Generated by Django 2.0.2 on 2018-04-07 16:29

import ckeditor.fields
from django.db import migrations, models
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='description',
            field=ckeditor.fields.RichTextField(default='Description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='location',
            field=models.CharField(default='Chicago', help_text="Example: 'Boston',                                                                                         'Chicago', 'Wheaton'", max_length=1024, verbose_name='Job Location'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='state',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], db_index=True, default='AL', max_length=100, no_check_for_status=True),
        ),
    ]
