# Generated by Django 2.0.2 on 2018-04-07 16:30

from django.db import migrations
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20180407_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_type',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='Full Time', max_length=100, no_check_for_status=True),
        ),
    ]
