# Generated by Django 2.0.2 on 2018-04-07 16:33

from django.db import migrations, models
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_job_job_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='additional_instructions',
            field=models.TextField(default='Additional'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='company_logo',
            field=models.ImageField(default='fdafs', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='company_name',
            field=models.CharField(default='CMallon', max_length=1024, verbose_name='Company Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='company_url',
            field=models.CharField(default='Test', max_length=1024, verbose_name='Company URL'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='how_apply',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='email', max_length=100, no_check_for_status=True),
        ),
    ]
