# Generated by Django 2.0.2 on 2018-04-07 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_auto_20180407_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='apply',
            field=models.CharField(default='test', max_length=1024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='contact_email',
            field=models.CharField(default='cmallon@cmallon.com', help_text='This is for internal use only', max_length=1024, verbose_name='Contact Email Address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='contact_name',
            field=models.CharField(default='Christopher', help_text='This is for internal use only', max_length=1024, verbose_name='Contact Name'),
            preserve_default=False,
        ),
    ]
