# Generated by Django 2.0.2 on 2018-04-07 16:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_auto_20180407_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
