# Generated by Django 2.0.2 on 2018-04-07 16:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0007_job_featured'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCredits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credits', models.IntegerField()),
                ('unlimited', models.BooleanField(default=False)),
                ('cost', models.IntegerField()),
                ('paid', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Job Credits',
                'verbose_name_plural': 'Job Credits',
            },
        ),
        migrations.CreateModel(
            name='JobCreditsLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.JobCredits')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.Job')),
            ],
            options={
                'verbose_name': 'Line Item',
                'verbose_name_plural': 'Line Item',
            },
        ),
    ]
