# Generated by Django 2.0.2 on 2018-04-19 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultant',
            name='contact_main',
            field=models.CharField(max_length=1024, verbose_name='Primary Contact'),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='name',
            field=models.CharField(max_length=1024, verbose_name='Compnay Name'),
        ),
    ]
