# Generated by Django 2.0.2 on 2018-04-19 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultants', '0002_auto_20180419_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultant',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=255, verbose_name='Primary Contact Phone'),
        ),
    ]
