# Generated by Django 2.0.2 on 2018-04-19 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultants', '0003_auto_20180419_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultant',
            name='bio',
            field=models.TextField(blank=True),
        ),
    ]
