# Generated by Django 2.0.2 on 2018-04-19 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultants', '0004_consultant_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultant',
            name='bio',
            field=models.TextField(blank=True, help_text='Tell us more about your company'),
        ),
    ]
